
spring:
  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password

  jpa:
    generate-ddl: true
    open-in-view: false